//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstoneproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zc
    {
        public int zipcode { get; set; }
        public Nullable<int> skid { get; set; }
    
        public virtual sk sk { get; set; }
    }
}
